name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  uqa-tests:
    name: Playwright UQA Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run UQA tests
        run: npx playwright test --grep @UQA
        env:
          ENV: UQA
          UQA_BASE_URL: ${{ vars.UQA_BASE_URL }}

      - name: Upload UQA Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-uqa
          path: playwright-report/
          retention-days: 30

  pst-tests:
    name: Playwright PST Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run PST tests
        run: npx playwright test --grep @PST
        env:
          ENV: PST
          PST_USERNAME: ${{ secrets.PST_USERNAME}}
          PST_PASSWORD: ${{ secrets.PST_PASSWORD }}
          PST_BASE_URL: ${{ vars.PST_BASE_URL }}
          FIRSTNAME: ${{ vars.FIRSTNAME }}
          LASTNAME: ${{ vars.LASTNAME }}

      - name: Upload PST Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-pst
          path: playwright-report/
          retention-days: 30

